<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'HumusRbacNavigationModule\Module'                                => __DIR__ . '/src/HumusRbacNavigationModule/Module.php',
  'HumusRbacNavigationModule\Service\NavigationFactory'             => __DIR__ . '/src/HumusRbacNavigationModule/Service/NavigationFactory.php',
  'HumusRbacNavigationModule\Service\NavigationRbacListenerFactory' => __DIR__ . '/src/HumusRbacNavigationModule/Service/NavigationRbacListenerFactory.php',
  'HumusRbacNavigationModule\NavigationRbacListener'                => __DIR__ . '/src/HumusRbacNavigationModule/NavigationRbacListener.php',
);
